### ISSUE TITLE
[ documentation ] Jobs not executed when running `pipelight trigger`

### ISSUE THREAD

**Issue by yonas** [pipelight/pipelight#23]
```sh
❯ type pipelight
pipelight is /usr/local/bin/pipelight

❯ pipelight trigger --flag pre-commit --attach

❯ pipelight logs -vv

❯ ls .pipelight/logs/
 .pipelight/logs/
└──  _unlinked.json

❯ cat .pipelight/logs/_unlinked.json

❯ cat pipelight.yaml
```
```yaml
pipelines:
  - name: example
    steps:
      - name: first
        commands:
          - touch example.txt
          - ls
      - name: second
        commands:
          - ls
          - pwd
```

commit: [8e34128](https://github.com/pipelight/pipelight/commit/8e34128b7d05669ce74a634fedc961fb20daef3a)

**Comment by yonas** [comment]
Fixed by adding a trigger:

```yaml

    triggers:
      - branches:
        - main
      - actions:
        - pre-commit
```

Maybe we can update the documentation to make this a bit clearer.
