### ISSUE TITLE
Ruff output not displaying correctly

### ISSUE THREAD

**Issue by sheff49** [pipelight/pipelight#25]
When running a `format` job with `ruff check`, any errors fail to load as output. 

Given the pipeline of the following: 

```toml
[[pipelines]]
name =  "format"

[[pipelines.steps]]
name = "lint"
commands = ["ruff check"]
```

The following output is produced when the job is ran:

```
● Failed - Fri, 15 Nov 2024 02:00:00 +0000
branch: <my_branch>
action: manual
commit: <my_commit_hash>
pipeline: format (79ms)
│
╰─step: lint (79ms)
   │
   ╰─ruff check (79ms)
      │
      ╰─
```

This bug can be reproduced by creating a python file with some rust validation, such as an unused import, and running a ruff job
