### ISSUE TITLE
`pipelight trigger` Doesn't Work on macOS  

### ISSUE THREAD

**Issue by hi2code** [pipelight/pipelight#26]
### Issue: `pipelight trigger` Doesn't Work on macOS  

Hi, Thank you for creating such an awesome project! It's been incredibly helpful. However, I encountered a bug while using it on macOS. Specifically, the `pipelight trigger` command does not seem to work as expected.  

### Steps to Reproduce  

1. Create the following `pipelight.yaml` configuration file:  
   ```yaml  
   pipelines:  
     - name: prod  
       steps:  
         - name: first  
           commands:  
             - ls  
         - name: second  
           commands:  
             - echo prod pipeline  
     - name: test  
       steps:  
         - name: first  
           commands:  
             - echo test pipeline  
       triggers:  
         - branches:  
             - main  
         - actions:  
             - pre-commit  
   ```  

2. Run the following command:  
   ```bash  
   pipelight trigger --flag pre-commit --attach  
   ```  
3. The above command works fine, and triggers the execution of the command pipe run , but when I output process log, I observed the following behavior.

### Observed Behavior  

When running the command, I noticed that the pipeline name gets wrapped in double quotes (`"test"`), which causes the program to fail to find the pipeline:  

```bash  
pipelight run '"test"' --flag pre-commit --attach  
```  

Logs:  
```
2024-11-23T19:48:22.133931+08:00 TRACE switch::case - PostCommands(DetachableCommands(Run(Pipeline { name: Some("\"test\""), trigger: Trigger { flag: Some("pre-commit") } })))  
...  
Error: worklow::is::error  

  × Couldn't find pipeline: "test"  
  help: Available pipelines are:  
        
        prod  
        test  
```  

### Root Cause  

It seems the pipeline name is incorrectly quoted (`"test"` instead of `test`), leading to the error.  

### Attempted Fix  

I identified the issue but, as a Rust beginner, I am unsure how to implement the fix. I suspect the issue lies in how pipeline names are being parsed or passed to the command.  

### Expected Behavior  

The command should work without wrapping the pipeline name in quotes and correctly execute the pipeline.  

Thank you for your time and effort in maintaining this project! Let me know if you need more details or additional logs to help troubleshoot.  

Best regards.
